### ISSUE TITLE
setup.py not working properly

### ISSUE THREAD

**Issue by simeks** [blaylockbk/goes2go#2]
Hey!

First off, I just found this project and the archive it links to but this looks like an amazing resource!

Now to the issue: there seems to be a bug in `setup.py`. Running the script doesn't actually include the package and this seems to be the case with the release on PyPI as well. If you open the released wheel you'll notice the actual package is missing. The problem seems to be the use of `find_package`, which to my knowledge still relies on the `__init__.py` files to identify packages. So you either have to add an `__init__.py` or specify the package manually within the setup.py.

**Comment by blaylockbk** [comment]
Thanks for reporting this. I added the __init__.py to the directory and updated the package on PyPi.

This problem didn't come up last I tested it, but I could have done it wrong. Which version of python are you using? I'm using python 3.7 and 3.8 and haven't tested with lesser versions. At any rate, I hope this fixed it for you.

**Comment by simeks** [comment]
This might be something they've changed in later versions of setuptools. Anyway, now it seems to be working for me on Python 3.8 both through `pip install` and `setup.py install`. Thank you!
