### ISSUE TITLE
Use the yml installation environment to report an error

### ISSUE THREAD

**Issue by muyiaaaa** [blaylockbk/goes2go#21]
I use the  [environment.yml](https://github.com/blaylockbk/goes2go/blob/main/environment.yml) installation when an error is reported, please ask what is the reason

`ERROR: yaml.scanner.ScannerError: mapping values are not allowed here`
in xxxxxxx line 28,col 66

**Comment by blaylockbk** [comment]
I'm not sure what would cause this error. Can you give me any more information? Are you using conda to create the environment?

```bash
conda env create -f environment.yml
```

**Comment by blaylockbk** [comment]
Closing since I haven't heard from you for a while. But if you are still running into problems, feel free to reopen or create a new issue 😎
