### ISSUE TITLE
Data not returning as xarray

### ISSUE THREAD

**Issue by efamutimi** [blaylockbk/goes2go#3]
Hello,
I am not sure if I am missing something or not, but when I use the goes_timerange() function and request to return the data as an xarray, I get an error and the result does not return as an xarray. I am using jupyter notebook. Attached is a word document with screenshots of the code and the error. The code is just the sample code you provided in the documentation. 
Thank you!
[error.docx](https://github.com/blaylockbk/goes2go/files/6785475/error.docx)

**Comment by blaylockbk** [comment]
That's interesting. Nothing in the error message jumps out at me.
I got output when I ran that exact code using `Python 3.8` and `xarray 0.18.2` (using the goes2go on the master branch)...

![image](https://user-images.githubusercontent.com/6249613/124971952-a6da7300-dfde-11eb-8b12-4d0dfa860915.png)

**Comment by blaylockbk** [comment]
As a work around, you can leave off the reaturn_as='xarray' argument to just download the files, then open the files with xarray manually. That might help you bypass my buggy read_with_xarray and concatenate.

**Comment by efamutimi** [comment]
That is so odd! I am using Python 3.9. Could that make a difference? 
Thank you!

**Comment by blaylockbk** [comment]
I'm not sure. I would first check that the files were downloaded completely and that you can read them with xarray
```python
import xarray as xr
xr.open_dataset('C:\Users\elain\data\noaa-goes16/ABI-L2-MCMIPC/2021/001/01/OR_ABI-L2-MCMIPC-M6_G16_s20210010111176_e20210010113555_c20210010114103.nc')
```

**Comment by efamutimi** [comment]
No, I cannot. I get a unicode error...I copy/pasted the file name. The screenshot doesn't show it but xarray was imported beforehand. 
![image](https://user-images.githubusercontent.com/76504946/124980362-48bf8700-e002-11eb-9b5e-8208e7079974.png)

**Comment by blaylockbk** [comment]
With that unicode error, it seems there is something wrong with the string characters directing the file you are trying to open.

**Comment by efamutimi** [comment]
Okay I saw the mistake I did in the string, thank you. I am just disappointed that I can't get the files to display as an xarray since I have to work with two years worth of files and opening each one manually will take more time than I wanted. Thank you for the help nonetheless.
