### ISSUE TITLE
FOV of CONUS scan data

### ISSUE THREAD

**Issue by zxdawn** [blaylockbk/goes2go#4]
The `field_of_view` still gets the Full Disk FOV when the input is the CONUS data.

```
import xarray as xr
from glob import glob
from goes2go.tools import field_of_view

ds_abi = xr.open_dataset(glob('../data/GOES-16/ABI_L1/OR_ABI-L1b-RadC-M6C13_G16_s2020153000*')[0])
FOV_abi, geo_abi = field_of_view(ds_abi)

display(FOV_abi)
```

![image](https://user-images.githubusercontent.com/30388627/126972082-18f5d6e5-9302-43e1-b376-05256a99573f.png)

**Comment by blaylockbk** [comment]
yeah, this is something that could be enhanced. Right now, my intent was just to shows the satellite's field of view no matter the domain. But the ability to produce polygons of the CONUS and Mesoscale sector domains would be a useful feature I'll consider.

**Comment by blaylockbk** [comment]
I updated the `field_of_fiew` function to produce both a polygon for the full field of view of the ABI instrument and a domain of the ABI scan for the specific domain.

![image](https://user-images.githubusercontent.com/6249613/129951839-7c169820-0256-423b-b697-f9cf4671b40a.png)
![image](https://user-images.githubusercontent.com/6249613/129951852-08649e82-c7f5-41f3-9403-9312af78776e.png)
![image](https://user-images.githubusercontent.com/6249613/129951864-ffb9eaf9-c9db-4f52-9b76-d2802203a7a4.png)

**Comment by zxdawn** [comment]
Thanks for the nice update!
