### ISSUE TITLE
Add refresh option to s3 file enumeration

### ISSUE THREAD

**Issue by gshau** [blaylockbk/goes2go#5]
When calling `get_latest`, the `fs.ls` command returns a cached list of the files on s3.  Adding `refresh=True` (or having kwargs to set this) to the following  should allow an updates enumeration of files on s3:
https://github.com/blaylockbk/goes2go/blob/e4e1f1027732517ebee95b2728f346785030d096/goes2go/data.py#L128

**Comment by blaylockbk** [comment]
Nice find! And thanks for providing the solution. I made a rough change in the master branch to address this. Hope that fixes it for you.
