### ISSUE TITLE
DayLandCloudFire in accessors.py has wrong data return

### ISSUE THREAD

**Issue by fleegs79** [blaylockbk/goes2go#56]
Hello,

I believe there is a minor error in the `accessors.py` file for the DayLandCloudFire RGB.  It returns:  
```python
return ds["DayLandCloud"]
```
when it should be:
```python
return ds["DayLandCloudFire"]
```
When running the DayLandCloudFire RGB, I get an error for `ds["DayLandCloud"]` not existing. I adjusted my file to add Fire and it works without error. 

Really enjoying using your package.  Thank you for putting it together and sharing it!

fleegs79

**Comment by blaylockbk** [comment]
Thanks @fleegs79 for tracking down this bug and providing a solution. That makes it really easy to fix. I merged the change in the main branch and this will be included in the next release.
