### ISSUE TITLE
Struggling with installation

### ISSUE THREAD

**Issue by EmanuelCastanho** [blaylockbk/goes2go#71]
Hi,

I am trying to install goes2go on a different environment from the one provided by the .yml file, however it is not working.

Here is my code:

```
# conda create -n fast_code_test_2-env python=3.9
# conda activate fast_code_test_2-env
# conda install -c conda-forge goes2go


from goes2go import GOES

# Advanced Baseline Imager Level 2 Cloud and Moisture Imagery Full Disk
goes_east = GOES(satellite=16, product="ABI-L2-CMIP", domain='F')
#goes_west = GOES(satellite=18, product="ABI-L2-CMIP", domain='F')

# Download and read the latest data as an xarray Dataset
ds = goes_east.latest()

print(ds)
```

Here is the error I am getting:
`ImportError: cannot import name 'maybe_sync' from 'fsspec.asyn'`

_fsspec_ version 2023.6.0 is already installed.
_s3fs_ version 0.5.1 is already installed.

It would be useful to have the packages versions on the example _environment.yml_

Thank you

**Comment by EmanuelCastanho** [comment]
Solved after including the proper s3fs version.

```
conda create -n fast_code_test_2-env python=3.9
conda activate fast_code_test_2-env
conda install -c conda-forge goes2go=2023.4.2
conda install -c conda-forge s3fs=2023.6.0
```

**Comment by blaylockbk** [comment]
Thanks for bringing this to my attention. I may need to tag a specific version of s3fs in the build.
