### ISSUE TITLE
Error importing with pandas 2.1.1

### ISSUE THREAD

**Issue by csteele2** [blaylockbk/goes2go#75]
When attempting to import goes2go with pandas 2.1.1, I am greeted with

```
File timedeltas.pyx:1820, in pandas._libs.tslibs.timedeltas.Timedelta.__new__()

File timedeltas.pyx:650, in pandas._libs.tslibs.timedeltas.parse_timedelta_string()

File timedeltas.pyx:698, in pandas._libs.tslibs.timedeltas.timedelta_from_spec()

ValueError: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and are not supported.
```

It looks like that was [deprecated in pandas](https://github.com/pandas-dev/pandas/issues/16344) awhile ago, unless I have missed something.

**Comment by blaylockbk** [comment]
Thanks for reporting this. Looks like I need to update some code.

**Comment by blaylockbk** [comment]
If you want to open a pull request, feel free. Otherwise it might take me awhile to get there.

**Comment by csteele2** [comment]
It seems to only be on my apple silicon mac. Doesn't throw that fit elsewhere. I can dig a little more.

**Comment by csteele2** [comment]
Okay, I still have to look into where this all occurs in your code, but definitely the config.toml file that is generated is not compliant. Changing it there seemed to fix those same errors on another system using nearesttime. According to [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.html) (at least for 2.4.1), 'H', 'M' are not valid to use for timedeltas, and that should probably be changed to 'h' or 'hour' and 'm' or 'min' or the like.
