### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by ilmesi** [blaylockbk/goes2go#87]
Is there a new release date estimated in the short term?

The feature included by commit 21e409b ("Simplify config file generation on import") is really helpful to start using this library in complex deploys envs like lambdas, readonly fs, and such.

Thanks!

**Comment by blaylockbk** [comment]
Thank for the poke 😄 

https://pypi.org/project/goes2go/

Please open any issues you see. I can't promise a quick fix as goes2go has been pushed down my priority list, but usually someone out there opens a PR to fix an issue.
