### ISSUE TITLE
Customize behavior about were downloaded GOES data is saved

### ISSUE THREAD

**Issue by RavenV-tiff** [blaylockbk/goes2go#95]
I know there is the option to specify were to save downloaded data with save_dir. However, I expect goes2go to save the files in that directory not under subdirectories it creates at that location. As far as I can tell there's no options to disable this behavior unless I'm mistaken.

**Comment by blaylockbk** [comment]
Thanks for the feedback. Right now, the files preserve the folder structure used on AWS, but I can see that it might be useful to just dump files in a specified directory. I'll keep this in mind. I'm not regularly developing this repo, but may eventually get to this if I find some time.

**Comment by RavenV-tiff** [comment]
Hey Brian thanks for the response. Yeah, it's not that important of a feature implementation, but as a nice to have. I was able to easily enough modify the behavior of my scripts to search the downloaded GOES file structure. Keep up the good work!
