### ISSUE TITLE
The FireTempreture rgb composit it's in K and it should be in C

### ISSUE THREAD

**Issue by santimc** [blaylockbk/goes2go#96]
[As provided in the link the range of the red channel should be from 0 to 60 C°](http://rammb.cira.colostate.edu/training/visit/quick_guides/Fire_Temperature_RGB.pdf)

In the file rgb.py line 516 it reads

```py
  R, G, B = load_RGB_channels(C, (7, 6, 5))
  
  # Normalize each channel by the appropriate range of values (clipping happens in function)
 
  R = normalize(R, 273, 333) #<------------- this line
```
but load_RGB_channels alredy converts from K to C, so i think it should be 

```py
  R = normalize(R, 0, 60) 
```

**Comment by blaylockbk** [comment]
Correct! Thanks.

Grabbed this image today from [NESDIS](https://www.star.nesdis.noaa.gov/GOES/conus_band.php?sat=G16&band=FireTemperature&length=24)
![image](https://github.com/blaylockbk/goes2go/assets/6249613/4c63e426-941b-4889-b7ad-ff700c90489d)

When I do 
```python
from goes2go import GOES
from goes2go.rgb import load_RGB_channels, normalize, gamma_correction

import numpy as np
import matplotlib.pyplot as plt

ds = GOES().nearesttime("2024-07-06 1856")

R, G, B = load_RGB_channels(ds, (7, 6, 5))
R = normalize(R, 0, 60)
G = normalize(G, 0, 1.0)
B = normalize(B, 0, 0.75)
gamma = 0.4
R = gamma_correction(R, gamma)
RGB = np.dstack([R, G, B])
plt.imshow(RGB)
```
I get a matching image
![image](https://github.com/blaylockbk/goes2go/assets/6249613/f1cd3c0d-a254-4e1c-b33e-3b6900de0263)

But the current implementation with `R = normalize(R, 273, 333)` gives this, which is wrong.
![image](https://github.com/blaylockbk/goes2go/assets/6249613/a1bd7190-feea-40d6-87b3-b31772f324ca)
